### PR TITLE
"Song ratings" pop-up goes out of view when dragging over its title #425

### LINKED ISSUE #425: "Song ratings" pop-up goes out of view when dragging over its title.
1. Open a song ( https://vocadb.net/S/7234 )
2. Click on `X favorite(s), Y like(s)`
3. Click and drag over the blue title line
4. Scroll down to find the box
5. Repeat

### PR DESCRIPTION
**Pull request by Pyther99**
Fixes #425. Maybe needs to be tested on the beta site to ensure that there are no unwanted side effects

### CODE REVIEW

**Comment by ycanardeau** [comment]
@Pyther99 Is this PR still a work in progress?

**Comment by Pyther99** [comment]
@ycanardeau Yes, JQuery seems to set the position to `absolute` after a resize, which causes the bug to reappear.

**Comment by Pyther99** [comment]
Using fixed seems to be the best solution. Since you can't edit the entry while a menu is open anyway, I think the new UI behavior is acceptable.

**Comment by ycanardeau** [comment]
Deployed on the beta site.

**Comment by ycanardeau** [comment]
Deployed on the beta site.

**Comment by Pyther99** [comment]
@ycanardeau Are you sure? I can't find the latest changes in https://beta.vocadb.net/Content/css.css

**Comment by ycanardeau** [comment]
Oops.

**Comment by Pyther99** [comment]
Thanks for the quick response, everything seems to work now.

**Comment by ycanardeau** [comment]
Thanks!

**Pull request merged**
