### PR TITLE
Improved and updated Spanish translation #3

### PR DESCRIPTION
**Pull request by FranGamer1892**
I am starting to go through all resx files checking if the Spanish translation is in order. This is what I got until now.

### CODE REVIEW

**Comment by FranGamer1892** [comment]
Upon further examination, I believe that these commits can be pushed safely. Of course, I'll try working on more resx files as time goes on. Unfortunately, I don't seem to be getting any responses from other Spanish-speaking contributors so they can check my work.

**Comment by Untitled39** [comment]
Checked all new changes, everything seems good. 👍

**Comment by FranGamer1892** [comment]
Thank you!

**Comment by ycanardeau** [comment]
Thanks for the PR and review!

**Pull request merged**
