### PR TITLE
Fix contrast of placeholder in search field

### LINKED ISSUE #838: Bad contrast in the search field
grafik

### PR DESCRIPTION
**Pull request by Pyther99**
Closes #838

### CODE REVIEW

**Comment by ycanardeau** [comment]
@Pyther99 Could you please add a comment to the file?

**Comment by ycanardeau** [comment]
@andreoda Deployed on the beta site.

**Comment by ycanardeau** [comment]
@Pyther99 This causes bad contrast in the search field when focused. Please use the original color rather than `whitesmoke`.

**Comment by Pyther99** [comment]
@ycanardeau Sorry for the late reply. I think this was a problem due to some of the css changes I made for the alternate song creation form. Since this was not merged into main, the problem should be fixed now. I'l close this PR for now.

**Pull request closed without merging**
