### PR TITLE
Sort events on venue page by date

### PR DESCRIPTION
**Pull request by ycanardeau**
#657 The venues are sorted by date in *ascending* order.

### CODE REVIEW

**Review by Nefere256 — APPROVED** [review]
It looks okay. 

Thanks for changes!

**Comment by riipah** [comment]
Is this contract used anywhere else such as event series page? Is there any place where we would want to keep the sorting by series number, then date? 

Should the series number sorting still be kept as secondary sort in case date is not specified (the date field is optional)?

**Comment by ycanardeau** [comment]
Thanks for reviews! We don't need to keep the series number as secondary sort because [they're already sorted](https://github.com/VocaDB/vocadb/blob/98ca1ce58e878029cd427f7cd01ee001908bc800/VocaDbModel/Mapping/Venues/VenueMap.cs#L49).

**Comment by riipah** [comment]
As a general design idea, it's better to do sorting like this in the APIs (controller or data contract). The mappings can be changed independently, it's not easy to find out where the sort is used. It also doesn't work for unit tests obviously, because unit tests do not care about NHibernate mappings. If the list is already sorted, then sorting it again will be very fast thanks to quicksort.

**Comment by ycanardeau** [comment]
I see, thanks!

**Pull request merged**
