### PR TITLE
bilibili short link matchers

### PR DESCRIPTION
**Pull request by kateabr**
Closes https://github.com/VocaDB/community/issues/180

### CODE REVIEW

**Comment by ycanardeau** [comment]
Can you please add unit tests for this change?

By the way, I've invited you as a collaborator on the VocaDB repository.

**Comment by kateabr** [comment]
Thank you! Accepted :3

I tried to add some tests, but I keep having problems with the solution at both Rider and VS:
```
PS ...\vocadb> dotnet restore
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: Файл "...\vocadb\vocadb-loc\VocaDb.TouhouDb.Resources\VocaDb.TouhouDb.Resources.csproj" не найден. [...\vocadb\VocaDb.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: Файл "...\vocadb\vocadb-loc\VocaDb.UtaiteDbResources\VocaDb.UtaiteDb.Resources.csproj" не найден. [...\vocadb\VocaDb.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: Файл "...\vocadb\vocadb-loc\VocaDbModel.Resources\VocaDb.Model.Resources.csproj" не найден. [...\vocadb\VocaDb.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: Файл "...\vocadb\vocadb-loc\VocaDbWeb.Resources\VocaDbWeb.Resources.csproj" не найден. [...\vocadb\VocaDb.sln]
```
It says it can't locate those files, any idea why?

**Comment by ycanardeau** [comment]
Welcome! :3

Did you run `git submodule update --init --recursive`?

**Comment by kateabr** [comment]
It worked, thank you!
(I'm not very experienced with C#, plz bear with me 🙏 )

**Comment by ycanardeau** [comment]
No worries, thanks for the PR!

**Pull request merged**
