### PR TITLE
Artist url parser for twitter

### LINKED ISSUE #843: Artist url parser for twitter "@handle"
Add url helper for twitter links:

Typing "@{artist twitter}" would give the artist entry that has the twitter URL, similarly to "mylist/{id}" with NND mylist links: https://github.com/VocaDB/vocadb/blob/f77563e9ba12b386c69bcb4532ee919daa2cd752/VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs

It would be useful on song/album edit pages, since it's common to see artists credited that way.

### PR DESCRIPTION
**Pull request by Pyther99**
Closes #843.
I changed the suggested URL parser from `@{Twitter username}` to `t/{Twitter username}` because there are some artists who use @ at the beginning of their username (https://vocadb.net/Search?filter=@*&searchType=Artist). Perhaps more such specific website shortcuts could be implemented (e.g. p/ for piapro).

### CODE REVIEW

**Comment by ycanardeau** [comment]
@Pyther99 Deployed on the beta site.

**Comment by ycanardeau** [comment]
@Pyther99 Could you please add unit tests for [ArtistExternalUrlParser](https://github.com/VocaDB/vocadb/blob/585136f696bdff161acbd3c6e6599860a66d8386/Tests/Service/Helpers/ArtistExternalUrlParserTests.cs) and [ArtistSearch](https://github.com/VocaDB/vocadb/blob/585136f696bdff161acbd3c6e6599860a66d8386/Tests/Service/Search/Artists/ArtistSearchTests.cs)?

**Comment by ycanardeau** [comment]
@riipah Is it acceptable to add an artist URL parser for Twitter to [ArtistExternalUrlParser](https://github.com/VocaDB/vocadb/blob/18bd2a210954f285afd143755d035502d8a7e133/VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs#L17)? I'm asking because I'm not sure why `ArtistExternalUrlParser` was introduced in the first place.

**Comment by riipah** [comment]
I think it's ok, although I would add a comment in the linkMatchers field

**Comment by ycanardeau** [comment]
@riipah What kind of comment would you add?

**Comment by riipah** [comment]
`twitter.com/name` or `t/name`. I feel that whenever you have a regex that's a bit more complicated, it's good to have a comment explaining it.

**Comment by ycanardeau** [comment]
Thanks!

**Pull request merged**
