### PR TITLE
Twipla icon issue 403

### PR DESCRIPTION
**Pull request by riipah**

### CODE REVIEW

**Comment by riipah** [comment]
Note that updating the css file by hand is actually unnecessary, it's generated from the .less file automatically by Visual Studio.

**Comment by Move-Forward39** [comment]
Ah, I see. Thanks!

**Comment by Move-Forward39** [comment]
If I just updated the .less file on the GitHub site, would Visual Studio still automatically update the css file (like on your end maybe)?

**Comment by riipah** [comment]
Yeah, when I open the project in VS

**Pull request merged**
